# -*- coding: utf-8 -*-
######################################################################################
# Form implementation generated from reading ui file 'VOltcurrent2.ui'               #                                                                                  
# Created by: PyQt5 UI code generator 5.13.2                                         #
######################################################################################
# Made with Qt Designer for the 3rd Assignement of Digital Signal Processing Course  #
# Part of "X-Wing-IIR-Filtering"                                                     #
# Github link : https://github.com/Alexandros-Charitonidis/X-Wing-IIR-Filltering     #
# Univeristy of Glasgow                                                              #
# Authors: Alexandros Charitonidis                                                   #
#          Alessandro Tadema                                                         #
######################################################################################


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 828)
        MainWindow.setMinimumSize(QtCore.QSize(1117, 0))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/X-Wing.png"))
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")        
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(350, 710))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PitchGraph = PlotWidget(self.frame_2)
        self.PitchGraph.setMinimumSize(QtCore.QSize(331, 671))
        self.PitchGraph.setObjectName("PitchGraph")
        self.PitchGraph.plotItem.setTitle("Pitch Plot [deg]")
        self.PitchGraph.plotItem.setLabel('left',"Angle [deg]")
        self.PitchGraph.plotItem.setLabel('bottom',"Samples")
        self.horizontalLayout.addWidget(self.PitchGraph)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(350, 710))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RollGraph = PlotWidget(self.frame_3)
        self.RollGraph.setMinimumSize(QtCore.QSize(331, 671))
        self.RollGraph.setObjectName("RollGraph")
        self.RollGraph.plotItem.setTitle("Roll Plot [deg]")
        self.RollGraph.plotItem.setLabel('left',"Angle [deg]")
        self.RollGraph.plotItem.setLabel('bottom',"Samples")
        self.horizontalLayout_6.addWidget(self.RollGraph)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(385, 16666))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(350, 300))
        self.frame_5.setMaximumSize(QtCore.QSize(500, 400))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.frame_5)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.frame_14)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("1redpng.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.gridLayout_2.addWidget(self.frame_14, 0, 2, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_5)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.PitchBar = QtWidgets.QProgressBar(self.frame_12)
        self.PitchBar.setMinimumSize(QtCore.QSize(30, 0))
        self.PitchBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.PitchBar.setMouseTracking(False)
        self.PitchBar.setMinimum(0)
        self.PitchBar.setMaximum(360)
        self.PitchBar.setProperty("value", 24)
        self.PitchBar.setOrientation(QtCore.Qt.Vertical)
        self.PitchBar.setInvertedAppearance(False)
        self.PitchBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.PitchBar.setObjectName("PitchBar")
        self.horizontalLayout_10.addWidget(self.PitchBar)
        self.gridLayout_2.addWidget(self.frame_12, 0, 1, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame_5)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.RollBar = QtWidgets.QProgressBar(self.frame_15)
        self.RollBar.setMinimumSize(QtCore.QSize(30, 0))
        self.RollBar.setMinimum(0)
        self.RollBar.setMaximum(360)
        self.RollBar.setProperty("value", 24)
        self.RollBar.setOrientation(QtCore.Qt.Vertical)
        self.RollBar.setInvertedAppearance(False)
        self.RollBar.setObjectName("RollBar")
        self.horizontalLayout_11.addWidget(self.RollBar)
        self.gridLayout_2.addWidget(self.frame_15, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 295))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dial = QtWidgets.QDial(self.frame_6)
        self.dial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dial.setMaximum(2)
        self.dial.setPageStep(0)
        self.dial.setSliderPosition(0)
        self.dial.setTracking(True)
        self.dial.setOrientation(QtCore.Qt.Horizontal)
        self.dial.setInvertedAppearance(False)
        self.dial.setInvertedControls(False)
        self.dial.setWrapping(False)
        self.dial.setNotchTarget(3.0)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.verticalLayout_2.addWidget(self.dial)
        self.label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setMinimumSize(QtCore.QSize(321, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(295, 109))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.RollLcd = QtWidgets.QLCDNumber(self.frame_10)
        self.RollLcd.setObjectName("RollLcd")
        self.horizontalLayout_3.addWidget(self.RollLcd)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_10)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.PitchLcd = QtWidgets.QLCDNumber(self.frame_10)
        self.PitchLcd.setObjectName("PitchLcd")
        self.horizontalLayout_4.addWidget(self.PitchLcd)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.UnfilteredLcd = QtWidgets.QLCDNumber(self.frame_10)
        self.UnfilteredLcd.setObjectName("UnfilteredLcd")
        self.horizontalLayout_5.addWidget(self.UnfilteredLcd)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMaximumSize(QtCore.QSize(361, 195))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMaximumSize(QtCore.QSize(321, 195))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_8.setFont(font)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setMaximumSize(QtCore.QSize(71, 101))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/images/Uni_Glasgow_2017_arms.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.ShowFiltered = QtWidgets.QRadioButton(self.frame_8)
        self.ShowFiltered.setObjectName("ShowFiltered")
        self.gridLayout_4.addWidget(self.ShowFiltered, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_8, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_6.addWidget(self.frame)
        self.frame_11 = QtWidgets.QFrame(self.centralwidget)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem4 = QtWidgets.QSpacerItem(881, 7, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout_6.addWidget(self.frame_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IIR Filter on Accelerometer measurments"))
        self.label.setText(_translate("MainWindow", "Filtering frequency:   (slow) 0.5        1 (fast)"))
        self.label_3.setText(_translate("MainWindow", "Pitch [deg]"))
        self.label_4.setText(_translate("MainWindow", "Roll [deg]"))
        self.label_5.setText(_translate("MainWindow", "Unfitered Pitch [deg]"))
        self.label_8.setText(_translate("MainWindow", "Digital Signal Processing: 3rd Assignment IIR Filtering on an Accelerometer for High Frequency Turbulences and PAPI Lights"))
        self.ShowFiltered.setText(_translate("MainWindow", "Show Unfiltered"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "Copyright @ Alexandros Charitonidis 2508116C & Alessandro Tadema 2504971T"))

from pyqtgraph import PlotWidget # For the promoted widgets!
import Resources # Resources file to keep everything tidy and path the images to the code
#Of course needed to run as a module! 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
